#!/usr/bin/env node

require('shelljs/global');
var paths = require('./paths.js');

build();

function build() {
  rm('-rf', paths.targetMainDirectory);
  make(paths.mainDirectory, paths.mainFile, paths.targetFile);
}

function make(directory, source, target) {
  cd(directory);
  exec('elm-make --yes ' + source + ' --output ' + target);
}
