#!/usr/bin/env node

require('shelljs/global');
var open = require('open');
var path = require('path');
var paths = require('./paths.js');

cd(paths.testDirectory);
exec('elm-reactor', { async: true });
open(path.join('http://localhost:8000', path.join(paths.testElmDirectoryRelative, paths.testRootModule)));
open(paths.elmPackage);
