var path = require('path');

exports.root = path.join(path.dirname(process.argv[1]), '..');
  exports.sourceDirectory = path.join(exports.root, 'src');
    exports.mainDirectory = path.join(exports.sourceDirectory, 'main');
      exports.elmPackage = path.join(exports.mainDirectory, 'elm-package.json');
      var elmPackageContents = require(exports.elmPackage);
      exports.elmDirectoryRelative = elmPackageContents['source-directories'][0]
      exports.elmDirectory = path.join(exports.mainDirectory, exports.elmDirectoryRelative);
        exports.rootModule = elmPackageContents['exposed-modules'][0];
        exports.mainFile = path.join(path.join(exports.elmDirectory, exports.rootModule), 'Main.elm');
    exports.testDirectory = path.join(exports.sourceDirectory, 'test');
      exports.testElmPackage = path.join(exports.testDirectory, 'elm-package.json');
      var testElmPackageContents = require(exports.testElmPackage);
      exports.testElmDirectoryRelative = testElmPackageContents['source-directories'][0]
      exports.testElmDirectory = path.join(exports.testDirectory, exports.testElmDirectoryRelative);
      exports.testRootModule = testElmPackageContents['exposed-modules'][0];
  exports.targetDirectory = path.join(exports.root, 'target');
    exports.targetFile = path.join(exports.targetDirectory, 'elm.js')
