#!/usr/bin/env node

var path = require('path');
require('shelljs/global');

var currentBranch = exec('git rev-parse --abbrev-ref HEAD', { silent:true }).output;
var masterBranch = 'master';
if (currentBranch != (masterBranch + '\n')) {
  echo('Current branch has to be ' + masterBranch + '!');
  exit(1);
}
var status = exec('git status --porcelain', { silent:true }).output;
if (status != '') {
  echo('Working directory must be clean!');
  exit(1);
}

cd(path.dirname(process.argv[1]));
exec('./build');

cd('..');

var target = 'target';
var temp = 'temp';
mv(target, temp);
exec('git stash --include-untracked');

var pagesBranch = 'gh-pages';
exec('git checkout ' + pagesBranch);

var mainSite = 'index.html';
exec('git checkout ' + masterBranch + ' ' + mainSite);
exec('git stash pop');
rm('-rf', target);
mv(temp, target);

var compiledJavaScripts = target + '/scala-2.11/*.js';
exec('git add -f ' + mainSite + ' ' + compiledJavaScripts);

exec('git commit -am "Publish"');
exec('git push origin ' + pagesBranch);
exec('git checkout ' + masterBranch);