#!/usr/bin/env node

var path = require('path');
require('shelljs/global');

var currentBranch = exec('git rev-parse --abbrev-ref HEAD', { silent:true }).output;
var masterBranch = 'master';
if (currentBranch != (masterBranch + '\n')) {
  echo('Current branch has to be ' + masterBranch + '!');
  exit(1);
}
var status = exec('git status --porcelain', { silent:true }).output;
if (status != '') {
  echo('Working directory must be clean!');
  exit(1);
}

cd(path.dirname(process.argv[1]));
exec('./build');

cd('..');

var pagesBranch = 'gh-pages';
exec('git checkout ' + pagesBranch);

exec('git checkout ' + masterBranch + ' index.html');

exec('git add -f index.html target/scala-2.11/*.js');

exec('git commit -am "Publish"');
exec('git push origin ' + pagesBranch);
exec('git checkout ' + masterBranch);